<a href="https://colab.research.google.com/github/DanielSzarek/175IC-machine-learning/blob/main/zad%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

shop_data = {
    'size': ['L', np.nan, 'S', 'XL', 'L', 'M', np.nan, 'S', 'M', 'XL', np.nan, 'M', 'L', np.nan, 'XL', 'S', 'M', 'XL', np.nan, 'L'],
    'color': ['green', np.nan, 'black', 'white', 'blue', np.nan, np.nan, 'black', 'green', 'brown', 'red', 'black', 'white', 'black', 'green', 'red', 'white', 'blue', np.nan, 'pink'],
    'gender': ['female', 'female', 'female', 'male', 'male', 'female', 'male', 'female', np.nan, 'female', 'female', 'male', 'female', 'female', 'male', 'male', 'female', 'female', 'male', 'female'],
    'price': [149.0, 79.0, 70.0, 150.0, 85.0, 92.0, 15.0, 35.50, 49.99, np.nan, 250.0, 153.10, 125.85, 99.99, 100.99, 25.0, 85.0, 65.0, np.nan, 169.0],
    'weight': [380, np.nan, 350, np.nan, 250, 280, 350, 150, 160, np.nan, 210, 250, 300, 750, 500, 450, 175, 100, 125, 350],
    'bought': ['no', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'no', 'no']
}


df_shop_data_raw = pd.DataFrame(data=shop_data)
df = df_shop_data_raw.copy()

# Task 1 - remove record if 3 or more values are nan
df.dropna(thresh=len(df.keys())-2, inplace=True)
print(df)

# Task 2-4 - fill empty values in various ways
df['price'].fillna(df['price'].mean(), inplace=True)
df['weight'].fillna(df['weight'].interpolate(), inplace=True)
df['size'].fillna('allsize', inplace=True)
df['color'].fillna('white', inplace=True)
df['gender'].fillna('unisex', inplace=True)
print(df)

# Task 5 - new column with 3 specific class
df['cost'] = pd.cut(df['price'], bins = 3, labels=('cheap', 'normal_price', 'expensive'))
print(df)

# Task 6 - bought_yes column
df['bought_yes'] = df['bought'].apply(lambda x: 1 if 'yes' in x else 0)
print(df)

# Task 7 - get input data and output data then create train and test data
df_input = df[['size', 'color', 'gender', 'cost']]
df_output = df['bought_yes']

x_train, x_test, y_train, y_test = train_test_split(df_input, df_output)
print(x_train)
print(y_train)

   size  color  gender   price  weight bought
0     L  green  female  149.00   380.0     no
2     S  black  female   70.00   350.0    yes
3    XL  white    male  150.00     NaN     no
4     L   blue    male   85.00   250.0    yes
5     M    NaN  female   92.00   280.0    yes
6   NaN    NaN    male   15.00   350.0     no
7     S  black  female   35.50   150.0    yes
8     M  green     NaN   49.99   160.0     no
9    XL  brown  female     NaN     NaN     no
10  NaN    red  female  250.00   210.0    yes
11    M  black    male  153.10   250.0     no
12    L  white  female  125.85   300.0     no
13  NaN  black  female   99.99   750.0     no
14   XL  green    male  100.99   500.0    yes
15    S    red    male   25.00   450.0    yes
16    M  white  female   85.00   175.0    yes
17   XL   blue  female   65.00   100.0     no
19    L   pink  female  169.00   350.0     no
       size  color  gender       price  weight bought
0         L  green  female  149.000000   380.0     no
2         S  black  female   70.000000   350.0    yes
3        XL  white    male  150.000000   300.0     no
4         L   blue    male   85.000000   250.0    yes
5         M  white  female   92.000000   280.0    yes
6   allsize  white    male   15.000000   350.0     no
7         S  black  female   35.500000   150.0    yes
8         M  green  unisex   49.990000   160.0     no
9        XL  brown  female  101.201176   185.0     no
10  allsize    red  female  250.000000   210.0    yes
11        M  black    male  153.100000   250.0     no
12        L  white  female  125.850000   300.0     no
13  allsize  black  female   99.990000   750.0     no
14       XL  green    male  100.990000   500.0    yes
15        S    red    male   25.000000   450.0    yes
16        M  white  female   85.000000   175.0    yes
17       XL   blue  female   65.000000   100.0     no
19        L   pink  female  169.000000   350.0     no
       size  color  gender       price  weight bought          cost
0         L  green  female  149.000000   380.0     no  normal_price
2         S  black  female   70.000000   350.0    yes         cheap
3        XL  white    male  150.000000   300.0     no  normal_price
4         L   blue    male   85.000000   250.0    yes         cheap
5         M  white  female   92.000000   280.0    yes         cheap
6   allsize  white    male   15.000000   350.0     no         cheap
7         S  black  female   35.500000   150.0    yes         cheap
8         M  green  unisex   49.990000   160.0     no         cheap
9        XL  brown  female  101.201176   185.0     no  normal_price
10  allsize    red  female  250.000000   210.0    yes     expensive
11        M  black    male  153.100000   250.0     no  normal_price
12        L  white  female  125.850000   300.0     no  normal_price
13  allsize  black  female   99.990000   750.0     no  normal_price
14       XL  green    male  100.990000   500.0    yes  normal_price
15        S    red    male   25.000000   450.0    yes         cheap
16        M  white  female   85.000000   175.0    yes         cheap
17       XL   blue  female   65.000000   100.0     no         cheap
19        L   pink  female  169.000000   350.0     no  normal_price
       size  color  gender       price  weight bought          cost  bought_yes
0         L  green  female  149.000000   380.0     no  normal_price           0
2         S  black  female   70.000000   350.0    yes         cheap           1
3        XL  white    male  150.000000   300.0     no  normal_price           0
4         L   blue    male   85.000000   250.0    yes         cheap           1
5         M  white  female   92.000000   280.0    yes         cheap           1
6   allsize  white    male   15.000000   350.0     no         cheap           0
7         S  black  female   35.500000   150.0    yes         cheap           1
8         M  green  unisex   49.990000   160.0     no         cheap           0
9        XL  brown  female  101.201176   185.0     no  normal_price           0
10  allsize    red  female  250.000000   210.0    yes     expensive           1
11        M  black    male  153.100000   250.0     no  normal_price           0
12        L  white  female  125.850000   300.0     no  normal_price           0
13  allsize  black  female   99.990000   750.0     no  normal_price           0
14       XL  green    male  100.990000   500.0    yes  normal_price           1
15        S    red    male   25.000000   450.0    yes         cheap           1
16        M  white  female   85.000000   175.0    yes         cheap           1
17       XL   blue  female   65.000000   100.0     no         cheap           0
19        L   pink  female  169.000000   350.0     no  normal_price           0
       size  color  gender          cost
0         L  green  female  normal_price
7         S  black  female         cheap
11        M  black    male  normal_price
13  allsize  black  female  normal_price
12        L  white  female  normal_price
8         M  green  unisex         cheap
10  allsize    red  female     expensive
15        S    red    male         cheap
14       XL  green    male  normal_price
9        XL  brown  female  normal_price
16        M  white  female         cheap
5         M  white  female         cheap
4         L   blue    male         cheap
       size  color  gender          cost
6   allsize  white    male         cheap
19        L   pink  female  normal_price
3        XL  white    male  normal_price
17       XL   blue  female         cheap
2         S  black  female         cheap
0     0
7     1
11    0
13    0
12    0
8     0
10    1
15    1
14    1
9     0
16    1
5     1
4     1
Name: bought_yes, dtype: int64
6     0
19    0
3     0
17    0
2     1
Name: bought_yes, dtype: int64